version: '3.8'

services:
  frontend:
    build:
      context: ./pregnancy-food-checker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./pregnancy-food-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      FLASK_ENV: development
      GEMINI_API_KEY: ${GEMINI_API_KEY}

